---

instance_type: t2.medium
ec2_volume_size: 16

ec2_image_id: ami-08481eff064f39a84
ec2_volume_snapshot: snap-0b8d7894c93b6df7a


euler_job_minutes: 10 # individual job time in minutes
euler_cpu_cores: 4
euler_cpu_mem_per_core_mb: 3072
euler_gpu_number: 0 # e.g., 1 for GPU
euler_gpu_min_mem_per_gpu_mb: 0  # e.g., 2000 for GPU
euler_gpu_model: ~

euler_env: "gcc/8.2.0 python/3.9.9"  # e.g., "gcc/8.2.0 python_gpu/3.9.9" for GPU

euler_scratch_dir: "/cluster/scratch/{{ euler_user }}"

docker_image_id: "doe-ubuntu20"
docker_image_tag: "latest"
