---


- debug:
    msg: "-> client only"
  tags: [print_action]

- name: Update repositories cache and install required packages
  become: True
  apt:
    pkg:
    # TODO: add other required packages (only for client)
    - netcat
