---

- debug:
    msg: "-> small only"
  tags: [print_action]

- name: Update repositories cache and install required packages
  become: True
  apt:
    pkg:
    - python3.9
    update_cache: yes


- name: Download get-pip.py
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip for python (via script)
  ansible.builtin.shell:
    cmd: python3.9 /tmp/get-pip.py

- name: Download install-poetry.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
    dest: /tmp/install-poetry.py

- name: Install poetry with script install-poetry.py
  ansible.builtin.shell:
    cmd: python3.9 /tmp/install-poetry.py

- name: make path to poetry available in variable
  set_fact:
    poetry: /home/ubuntu/.local/bin/poetry

- name: Set config to create .venv folder in project directory
  ansible.builtin.shell:
    cmd: "{{ poetry }} config virtualenvs.in-project true"

- name: Install python packages with poetry (-> afterward can run {{ poetry }} run python demo.py)
  ansible.builtin.shell:
    cmd: "{{ poetry }} install"
    chdir: "{{ exp_code_dir }}/demo_project"