---

instance_type: t2.medium
ec2_volume_size: 16

ec2_image_id: ami-08481eff064f39a84
ec2_volume_snapshot: snap-0b8d7894c93b6df7a



euler_job_minutes: 10 # individual job time in minutes
euler_cpu_cores: 1
euler_cpu_mem_per_core_mb: 3072
euler_gpu_number: 0
euler_gpu_min_mem_per_gpu_mb: 0
euler_gpu_model: ~
euler_env: "gcc/8.2.0 python/3.9.9"

euler_scratch_dir: "/cluster/scratch/{{ euler_user }}"

docker_image_id: "doe-ubuntu20"
docker_image_tag: "latest"